### ISSUE TITLE
push版本过低问题

### ISSUE THREAD

**Issue by shiwl0329** [nowa-webpack/template-salt#2]
handlePush() {
    window.salt.router.push({
      id: 'popwin',
      url: './popwin.html',
      anim: 2,
      needPost: true,
      param: {
        foo: 1,
        bar: 2,
      },
    }).then().catch((e) => {
      if (e.errorCode === 1001) {
        location.href = './popwin.html';
      }
    });
  }
这段代码执行的就是catch，报错的e（错误）就是版本问题，最新版本是多少？

**Comment by gbk** [comment]
0.9.9，好像最新的版本已经改了，你更新一下脚手架试试？
