### ISSUE TITLE
nowa init page命令不能用，nowa init mod可以用

### ISSUE THREAD

**Issue by raohuangxing** [nowa-webpack/template-salt#3]
该怎么处理

**Comment by gbk** [comment]
能否详细描述一下现象（包括截图或者视频）以及你的期望？

**Comment by raohuangxing** [comment]
![4345](https://user-images.githubusercontent.com/38023804/45667915-88650d80-bb4d-11e8-90d6-a4ca50fa58f7.png)
用nowa命令创建mod模块可以用的，创建页面不能用，以前都是可以的

**Comment by raohuangxing** [comment]
我用nowa的终端试过，也不行

**Comment by raohuangxing** [comment]
![7](https://user-images.githubusercontent.com/38023804/45668148-4e483b80-bb4e-11e8-8c12-ba3d2cee6925.png)
用的这个模板

**Comment by raohuangxing** [comment]
大佬帮帮忙啊，不然我要复制这些页面，改起来不方便

**Comment by gbk** [comment]
nodejs 版本是多少？
以前可以，现在不行了？nowa-init 有两年没改过了呢…

**Comment by raohuangxing** [comment]
![1285](https://user-images.githubusercontent.com/38023804/45726854-b1d87480-bbf3-11e8-9c32-1bb01885fe5d.png)
是的，以前nowa init page命令可以用，我也没有改这些命令文件。重启了也不起作用

**Comment by raohuangxing** [comment]
不行的话，我都卸载了重新装一次。就怕安装出错

**Comment by raohuangxing** [comment]
用npm安装这几个命令应该怎么写啊。 npm i nowa-init 。后面要不要-g，-s啊

**Comment by raohuangxing** [comment]
以前不习惯用这些命令，现在才发现命令是真的好用

**Comment by raohuangxing** [comment]
nowa的问题在网上都问不到

**Comment by gbk** [comment]
https://nowa-webpack.github.io/docs/chang_jian_wen_ti.html
参考这个，用 powershell 把 nowa 插件删了重装试试
